"""
Exact quasiparticle reduction of a spectral/dispersive term whose spectral constraints span
all loop frequencies.

`loop_energies` stores the solved loop frequencies as exact symbolic `EnergyForm`s in the
corresponding `loop_basis_indices`. `pivot_spectral_lines` records the canonical spectral
lines used to perform the frequency integrations. `support` contains only the residual energy
shells and principal-value denominators. `factor` is the exact rational Jacobian/support
normalisation generated by the reduction; spectral-function `2π` conventions are deliberately
not folded into this factor.
"""
struct FullRankFrequencyReduction{S<:Statistics}
    loop_basis_indices::Vector{Int}
    loop_energies::Vector{EnergyForm{S}}
    pivot_spectral_lines::Vector{Int}
    support::FrequencySupport{S}
    factor::EnergyCoefficient
end

"""Return the momentum-basis indices whose loop frequencies were eliminated."""
function loop_frequency_basis_indices(reduction::FullRankFrequencyReduction)
    return reduction.loop_basis_indices
end

"""Return the exact solved loop-frequency energies in canonical loop-basis order."""
loop_frequency_energies(reduction::FullRankFrequencyReduction) = reduction.loop_energies

"""Return the canonical spectral-line indices chosen as frequency-integration pivots."""
spectral_pivot_lines(reduction::FullRankFrequencyReduction) = reduction.pivot_spectral_lines

"""Return the residual shell/PV support after full-rank frequency elimination."""
frequency_support(reduction::FullRankFrequencyReduction) = reduction.support

"""Return the exact rational Jacobian/support factor generated by frequency elimination."""
frequency_factor(reduction::FullRankFrequencyReduction) = reduction.factor

function Base.isequal(
    a::FullRankFrequencyReduction{S}, b::FullRankFrequencyReduction{S}
) where {S<:Statistics}
    return isequal(a.loop_basis_indices, b.loop_basis_indices) &&
           isequal(a.loop_energies, b.loop_energies) &&
           isequal(a.pivot_spectral_lines, b.pivot_spectral_lines) &&
           isequal(a.support, b.support) &&
           a.factor == b.factor
end
Base.:(==)(a::FullRankFrequencyReduction, b::FullRankFrequencyReduction) = isequal(a, b)
function Base.hash(reduction::FullRankFrequencyReduction, h::UInt)
    return hash(
        (
            reduction.loop_basis_indices,
            reduction.loop_energies,
            reduction.pivot_spectral_lines,
            reduction.support,
            reduction.factor,
        ),
        hash(FullRankFrequencyReduction, h),
    )
end

function _external_frequency_basis_index(term::SpectralDispersiveTerm)
    basis = momentum_basis(term)
    external = external_wigner_momentum(term)
    for (i, variable) in enumerate(basis)
        isequal(variable, external) && return i
    end
    return throw(
        ArgumentError("external Wigner momentum is not present in the term momentum basis")
    )
end

function _loop_frequency_basis_indices(term::SpectralDispersiveTerm)
    basis = momentum_basis(term)
    external_index = _external_frequency_basis_index(term)
    return Int[i for i in eachindex(basis.variables) if i != external_index]
end

"""Number of independent loop-frequency variables implied by the routed momentum basis."""
function loop_frequency_count(term::SpectralDispersiveTerm)
    return length(_loop_frequency_basis_indices(term))
end

function _exact_frequency_rank(matrix::Matrix{EnergyCoefficient})::Int
    nrows, ncols = size(matrix)
    (iszero(nrows) || iszero(ncols)) && return 0
    work = copy(matrix)
    rank = 0
    for col in 1:ncols
        pivot = 0
        for row in (rank + 1):nrows
            if !iszero(work[row, col])
                pivot = row
                break
            end
        end
        iszero(pivot) && continue

        rank += 1
        if pivot != rank
            for j in col:ncols
                work[rank, j], work[pivot, j] = work[pivot, j], work[rank, j]
            end
        end

        pivot_value = work[rank, col]
        for row in (rank + 1):nrows
            factor = work[row, col]
            iszero(factor) && continue
            ratio = factor / pivot_value
            for j in col:ncols
                work[row, j] -= ratio * work[rank, j]
            end
        end
        rank == nrows && break
    end
    return rank
end

function _spectral_loop_matrix(term::SpectralDispersiveTerm)
    loop_indices = _loop_frequency_basis_indices(term)
    spectral_lines = Int[]
    lines = kinetic_lines(term.carrier)
    kinds = spectral_dispersive_kinds(term)
    for i in eachindex(lines)
        kinds[i] === CollisionSpectral && push!(spectral_lines, i)
    end

    matrix = zeros(EnergyCoefficient, length(spectral_lines), length(loop_indices))
    for (row, line_index) in enumerate(spectral_lines)
        routed = momentum(lines[line_index])
        for (col, basis_index) in enumerate(loop_indices)
            matrix[row, col] = routed[basis_index]
        end
    end
    return matrix, spectral_lines
end

"""Rank of the spectral on-shell constraints with respect to loop frequencies."""
function spectral_frequency_rank(term::SpectralDispersiveTerm)::Int
    matrix, _ = _spectral_loop_matrix(term)
    return _exact_frequency_rank(matrix)
end

function _first_full_rank_rows(matrix::Matrix{EnergyCoefficient}, target_rank::Int)
    target_rank == 0 && return Int[]
    selected = Int[]
    current_rank = 0
    for row in axes(matrix, 1)
        candidate_rows = vcat(selected, row)
        candidate = matrix[candidate_rows, :]
        candidate_rank = _exact_frequency_rank(candidate)
        if candidate_rank > current_rank
            push!(selected, row)
            current_rank = candidate_rank
            current_rank == target_rank && return selected
        end
    end
    return throw(ArgumentError("spectral constraints do not span all loop frequencies"))
end

function _exact_inverse_and_determinant(matrix::Matrix{EnergyCoefficient})
    nrows, ncols = size(matrix)
    nrows == ncols || throw(DimensionMismatch("frequency pivot matrix must be square"))
    if iszero(nrows)
        return zeros(EnergyCoefficient, 0, 0), one(EnergyCoefficient)
    end

    work = copy(matrix)
    inverse = zeros(EnergyCoefficient, nrows, nrows)
    for i in 1:nrows
        inverse[i, i] = one(EnergyCoefficient)
    end

    determinant = one(EnergyCoefficient)
    determinant_sign = one(Int8)
    for col in 1:ncols
        pivot = 0
        for row in col:nrows
            if !iszero(work[row, col])
                pivot = row
                break
            end
        end
        iszero(pivot) && throw(ArgumentError("frequency pivot matrix is singular"))

        if pivot != col
            for j in 1:ncols
                work[col, j], work[pivot, j] = work[pivot, j], work[col, j]
                inverse[col, j], inverse[pivot, j] = inverse[pivot, j], inverse[col, j]
            end
            determinant_sign = -determinant_sign
        end

        pivot_value = work[col, col]
        determinant *= pivot_value
        for j in 1:ncols
            work[col, j] /= pivot_value
            inverse[col, j] /= pivot_value
        end

        for row in 1:nrows
            row == col && continue
            factor = work[row, col]
            iszero(factor) && continue
            for j in 1:ncols
                work[row, j] -= factor * work[col, j]
                inverse[row, j] -= factor * inverse[col, j]
            end
        end
    end

    return inverse, determinant_sign * determinant
end

function _line_frequency_rhs(
    line::KineticLine{S}, target_energy::EnergyForm{S}, external_index::Int
) where {S<:Statistics}
    routed = momentum(line)
    energy = EnergyForm(DispersionAtom(line.family, routed))
    return energy - routed[external_index] * target_energy
end

function _combine_frequency_energies(
    weights::AbstractVector{EnergyCoefficient},
    forms::AbstractVector{EnergyForm{S}},
    basis_size::Int,
) where {S<:Statistics}
    length(weights) == length(forms) || throw(
        DimensionMismatch("frequency-solution row does not match pivot right-hand side")
    )
    out = EnergyForm{S}(basis_size)
    for i in eachindex(weights, forms)
        iszero(weights[i]) && continue
        out = out + weights[i] * forms[i]
    end
    return out
end

function _frequency_mismatch(
    line::KineticLine{S},
    loop_indices::Vector{Int},
    loop_energies::Vector{EnergyForm{S}},
    target_energy::EnergyForm{S},
    external_index::Int,
) where {S<:Statistics}
    length(loop_indices) == length(loop_energies) ||
        throw(DimensionMismatch("loop-frequency solution has inconsistent length"))
    routed = momentum(line)
    mismatch =
        routed[external_index] * target_energy -
        EnergyForm(DispersionAtom(line.family, routed))
    for i in eachindex(loop_indices, loop_energies)
        coefficient = routed[loop_indices[i]]
        iszero(coefficient) && continue
        mismatch = mismatch + coefficient * loop_energies[i]
    end
    return mismatch
end

"""
    full_rank_frequency_reduction(term, target)

Project the external frequency onto the quasiparticle energy of `target` and integrate all loop
frequencies using a deterministic full-rank subset of the term's spectral factors. Remaining
spectral factors become canonical `EnergyShell`s and dispersive factors become canonical
`PrincipalValueSupport`s.

This routine is intentionally strict. It rejects nonzero equal-time regularisation shifts,
rank-deficient spectral systems, redundant residual `δ(0)` constraints, and dispersive
`PV(1/0)` singularities. Those cases require the dedicated Trotter or Kramers--Kronig rules and
must not be silently approximated by the generic reducer.

The returned rational factor contains only exact delta-function Jacobians and support-scale
normalisation. No spectral-function `2π` convention is assumed here.
"""
function full_rank_frequency_reduction(
    term::SpectralDispersiveTerm{S}, target::FieldFamily{S}
) where {S<:Statistics}
    lines = kinetic_lines(term.carrier)
    for line in lines
        iszero(regularisation_shift(line)) || throw(
            ArgumentError(
                "shifted equal-time line requires dedicated Trotter frequency reduction"
            ),
        )
    end

    basis = momentum_basis(term)
    external_index = _external_frequency_basis_index(term)
    loop_indices = _loop_frequency_basis_indices(term)
    target_momentum = basis_momentum(basis, external_index)
    target_energy = EnergyForm(DispersionAtom(target, target_momentum))

    matrix, spectral_lines = _spectral_loop_matrix(term)
    nloops = length(loop_indices)
    rank = _exact_frequency_rank(matrix)
    rank == nloops || throw(
        ArgumentError(
            "spectral frequency rank $rank does not span $nloops loop-frequency variables",
        ),
    )

    pivot_rows = _first_full_rank_rows(matrix, nloops)
    pivot_lines = Int[spectral_lines[row] for row in pivot_rows]
    pivot_matrix = matrix[pivot_rows, :]
    inverse, determinant = _exact_inverse_and_determinant(pivot_matrix)

    pivot_rhs = EnergyForm{S}[
        _line_frequency_rhs(lines[line_index], target_energy, external_index) for
        line_index in pivot_lines
    ]
    loop_energies = Vector{EnergyForm{S}}(undef, nloops)
    basis_size = length(basis)
    for loop in 1:nloops
        loop_energies[loop] = _combine_frequency_energies(
            view(inverse, loop, :), pivot_rhs, basis_size
        )
    end

    factor = inv(abs(determinant))
    shells = EnergyShell{S}[]
    principal_values = PrincipalValueSupport{S}[]
    pivot_mask = falses(length(lines))
    for line_index in pivot_lines
        pivot_mask[line_index] = true
    end

    kinds = spectral_dispersive_kinds(term)
    for line_index in eachindex(lines)
        if kinds[line_index] === CollisionSpectral && pivot_mask[line_index]
            continue
        end

        mismatch = _frequency_mismatch(
            lines[line_index], loop_indices, loop_energies, target_energy, external_index
        )
        if kinds[line_index] === CollisionSpectral
            iszero(mismatch) && throw(
                ArgumentError(
                    "residual spectral constraint collapsed to δ(0); a dedicated repeated-shell rule is required",
                ),
            )
            shell, support_factor = energy_shell(mismatch)
            factor *= support_factor
            push!(shells, shell)
        else
            iszero(mismatch) && throw(
                ArgumentError(
                    "dispersive denominator collapsed to PV(1/0); a dedicated causal identity is required",
                ),
            )
            support, support_factor = principal_value_support(mismatch)
            factor *= support_factor
            push!(principal_values, support)
        end
    end

    return FullRankFrequencyReduction{S}(
        loop_indices,
        loop_energies,
        pivot_lines,
        FrequencySupport(shells, principal_values),
        factor,
    )
end
