"""
Structural witness for one locally reducible equal-time/Trotter loop frequency.

`line_index` identifies the shifted spectral/dispersive factor. `loop_basis_index` identifies a
loop-frequency variable that occurs in that factor and in no other active propagator factor.
`loop_coefficient` is the exact coefficient of that variable in the routed line frequency and
therefore fixes the integration Jacobian.

A zero witness means that no shifted line has exactly one structurally isolated active
loop-frequency variable. It does not mean that the shifted contribution vanishes.
"""
struct TrotterFrequencyWitness
    line_index::Int
    loop_basis_index::Int
    loop_coefficient::EnergyCoefficient
end

TrotterFrequencyWitness() = TrotterFrequencyWitness(0, 0, zero(EnergyCoefficient))

"""Return whether this witness proves a locally reducible isolated equal-time loop."""
function has_isolated_trotter_frequency(witness::TrotterFrequencyWitness)
    return !iszero(witness.line_index) &&
           !iszero(witness.loop_basis_index) &&
           !iszero(witness.loop_coefficient)
end

"""
Frequency-integration state for one exact spectral/dispersive term.

The full `MomentumBasis` remains in `term` even after a loop frequency is integrated, because
the corresponding spatial loop momentum is still a physical phase-space variable. The two
index vectors therefore record only which propagator factors and loop *frequencies* remain
active in subsequent frequency algebra. `factor` contains exact factors generated by already
performed frequency integrations.
"""
struct FrequencyIntegrationState{S<:Statistics,E1,E2}
    term::SpectralDispersiveTerm{S,E1,E2}
    active_line_indices::Vector{Int}
    active_loop_basis_indices::Vector{Int}
    factor::ComplexRationals
end

function FrequencyIntegrationState(term::SpectralDispersiveTerm{S,E1,E2}) where {S,E1,E2}
    return FrequencyIntegrationState{S,E1,E2}(
        term,
        collect(eachindex(kinetic_lines(term.carrier))),
        _loop_frequency_basis_indices(term),
        one(ComplexRationals),
    )
end

function _frequency_incidence_count(state::FrequencyIntegrationState, basis_index::Int)
    lines = kinetic_lines(state.term.carrier)
    count = 0
    for line_index in state.active_line_indices
        iszero(momentum(lines[line_index])[basis_index]) || (count += 1)
    end
    return count
end

"""
    trotter_frequency_witness(state)

Find the first shifted active line whose equal-time frequency can be integrated locally without
changing any active spectator factor.

An active loop-frequency variable is a valid witness only when it appears in the shifted line
and in no other active propagator factor. Exactly one such variable must be associated with the
shifted line; multiple unique variables would leave an unconstrained frequency volume after
collapsing a single propagator and are therefore not assigned a local rule here.

The criterion is purely affine/routing based. It does not inspect perturbative order, topology,
or line count.
"""
function trotter_frequency_witness(state::FrequencyIntegrationState)
    lines = kinetic_lines(state.term.carrier)

    for line_index in state.active_line_indices
        line = lines[line_index]
        iszero(regularisation_shift(line)) && continue
        routed = momentum(line)
        isolated_index = 0
        isolated_count = 0

        for basis_index in state.active_loop_basis_indices
            coefficient = routed[basis_index]
            iszero(coefficient) && continue
            _frequency_incidence_count(state, basis_index) == 1 || continue
            isolated_count += 1
            isolated_index = basis_index
            isolated_count > 1 && break
        end

        isolated_count == 1 || continue
        coefficient = convert(EnergyCoefficient, routed[isolated_index])
        return TrotterFrequencyWitness(line_index, isolated_index, coefficient)
    end

    return TrotterFrequencyWitness()
end

"""Find an isolated Trotter-frequency witness in an otherwise unreduced term."""
function trotter_frequency_witness(term::SpectralDispersiveTerm)
    return trotter_frequency_witness(FrequencyIntegrationState(term))
end

"""Return the shifted line selected by a Trotter witness."""
function trotter_frequency_line(
    term::SpectralDispersiveTerm, witness::TrotterFrequencyWitness
)
    has_isolated_trotter_frequency(witness) ||
        throw(ArgumentError("Trotter witness does not identify an isolated frequency"))
    return kinetic_lines(term.carrier)[witness.line_index]
end

"""
    trotter_equal_time_factor(term, witness)

Return the exact frequency-integration factor for the witnessed one-sided equal-time line.

For nonzero relative shift `s`, only `sign(s)` survives the `ε → 0⁺` limit. In package
conventions,

```text
A(0ˢ) = 1,
D(0ˢ) = -(i/2) sign(s).
```

The returned value also contains the exact `1/abs(c)` Jacobian for routed line frequency
`ω_line = c*ω_loop + ...`.

A shifted factor carrying `DistributionWeight` is deliberately rejected: the integral of
`F(ω)A(ω)` is not fixed by the equal-time canonical (anti)commutator alone.
"""
function trotter_equal_time_factor(
    term::SpectralDispersiveTerm, witness::TrotterFrequencyWitness
)::ComplexRationals
    line = trotter_frequency_line(term, witness)
    statistical_weight(line) === NoStatisticalWeight || throw(
        ArgumentError(
            "statistically weighted shifted line has no universal local equal-time factor",
        ),
    )

    shift = regularisation_shift(line)
    iszero(shift) && throw(ArgumentError("Trotter witness selected an unshifted line"))
    jacobian = inv(abs(witness.loop_coefficient))
    kind = spectral_dispersive_kinds(term)[witness.line_index]

    local_factor = if kind === CollisionSpectral
        one(ComplexRationals)
    elseif kind === CollisionDispersive
        convert(ComplexRationals, -(sign(Int(shift)) // 2) * im)
    else
        error("unsupported spectral/dispersive kind in Trotter reduction")
    end

    return convert(ComplexRationals, jacobian) * local_factor
end

"""
    eliminate_trotter_frequency(state, witness)

Integrate one certified isolated equal-time loop frequency while preserving its spatial
momentum variable in the source term's `MomentumBasis`.

The witnessed propagator factor is removed only from the active frequency algebra, and the
witnessed loop-basis index is removed only from the active frequency set. This separation is
essential: equal-time frequency integration does not remove the later spatial momentum
integration.
"""
function eliminate_trotter_frequency(
    state::FrequencyIntegrationState{S,E1,E2}, witness::TrotterFrequencyWitness
) where {S<:Statistics,E1,E2}
    has_isolated_trotter_frequency(witness) ||
        throw(ArgumentError("cannot eliminate an unresolved Trotter frequency"))
    witness.line_index in state.active_line_indices ||
        throw(ArgumentError("Trotter witness line is no longer active"))
    witness.loop_basis_index in state.active_loop_basis_indices ||
        throw(ArgumentError("Trotter witness frequency is no longer active"))

    expected = trotter_frequency_witness(state)
    expected == witness || throw(
        ArgumentError(
            "Trotter witness is not the canonical isolated frequency of this state"
        ),
    )

    active_lines = Int[
        index for index in state.active_line_indices if index != witness.line_index
    ]
    active_frequencies = Int[
        index for
        index in state.active_loop_basis_indices if index != witness.loop_basis_index
    ]
    factor = state.factor * trotter_equal_time_factor(state.term, witness)
    return FrequencyIntegrationState{S,E1,E2}(
        state.term, active_lines, active_frequencies, factor
    )
end

"""
Eliminate isolated shifted loop frequencies deterministically until no certified local Trotter
witness remains. Any remaining shifted active factor requires a more general finite-shift
contour rule and is intentionally left in the returned state.
"""
function eliminate_isolated_trotter_frequencies(state::FrequencyIntegrationState)
    current = state
    while true
        witness = trotter_frequency_witness(current)
        has_isolated_trotter_frequency(witness) || return current
        current = eliminate_trotter_frequency(current, witness)
    end
end

function _active_spectral_constraints(
    state::FrequencyIntegrationState{S}, target::FieldFamily{S}
) where {S<:Statistics}
    term = state.term
    lines = kinetic_lines(term.carrier)
    basis = momentum_basis(term)
    external_index = _external_frequency_basis_index(term)
    target_momentum = basis_momentum(basis, external_index)
    target_energy = EnergyForm(DispersionAtom(target, target_momentum))
    kinds = spectral_dispersive_kinds(term)

    constraints = AffineSpectralConstraint{S}[]
    line_indices = Int[]
    shifts = Int8[]
    for line_index in state.active_line_indices
        kinds[line_index] === CollisionSpectral || continue
        line = lines[line_index]
        coefficients = EnergyCoefficient[
            momentum(line)[index] for index in state.active_loop_basis_indices
        ]
        rhs = _line_frequency_rhs(line, target_energy, external_index)
        push!(constraints, AffineSpectralConstraint{S}(coefficients, rhs))
        push!(line_indices, line_index)
        push!(shifts, regularisation_shift(line))
    end
    return constraints, line_indices, shifts
end

"""
Analyse spectral-shell dependence after some loop frequencies or propagator factors have already
been integrated.

Only active spectral factors and active loop-frequency coordinates participate. The original
momentum basis is intentionally retained in every `EnergyForm`, because eliminating a loop
frequency does not eliminate its spatial phase-space momentum.
"""
function analyze_spectral_dependencies(
    state::FrequencyIntegrationState{S}, target::FieldFamily{S}
) where {S<:Statistics}
    constraints, line_indices, shifts = _active_spectral_constraints(state, target)
    return SpectralDependencyAnalysis{S}(
        analyze_spectral_dependencies(constraints), line_indices, shifts
    )
end
